### ISSUE TITLE
Pluggable page transitions

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#193]
Allow choice of page transitions. Some interesting ones:

http://hakim.se/experiments/css3-3d-slideshow

page flipping —

``` css
.csstransforms3d .grid {
 -webkit-transform-origin: 0% 50% 50%;
 -webkit-transition: all 0.5s ease-out;
 -moz-transition: all 0.5s ease-out;
 -o-transition: all 0.5s ease-out;
 transition: all 0.5s ease-out; }

.csstransforms3d #previousPage {
 -webkit-transform: perspective(2000) rotateY(-90deg) !important;
 -moz-transform: perspective(2000) rotateY(-90deg) !important;
 -o-transform: perspective(2000) rotateY(-90deg) !important;
 transform: perspective(2000) rotateY(-90deg) !important; }

.csstransforms3d #nextPage {
 -webkit-transform: perspective(2000) rotateY(90deg) !important;
 -moz-transform: perspective(2000) rotateY(90deg) !important;
 -o-transform: perspective(2000) rotateY(90deg) !important;
 transform: perspective(2000) rotateY(90deg) !important; }
```

cover flow —

``` css
.csstransforms3d .grid {
 -webkit-transform-origin: 50% 50% 50%;
 -webkit-transition: all 0.2s ease-out;
 -moz-transition: all 0.2s ease-out;
 -o-transition: all 0.2s ease-out;
 transition: all 0.2s ease-out; }

.csstransforms3d #previousPage {
 -webkit-transform: perspective(1000) rotateY(20deg) translate3d(0%, 0, -400px) !important;
 -moz-transform: perspective(1000) rotateY(20deg) translate3d(0%, 0, -400px) !important;
 -o-transform: perspective(1000) rotateY(20deg) translate3d(0%, 0, -400px) !important;
 transform: perspective(1000) rotateY(20deg) translate3d(0%, 0, -400px) !important; }

.csstransforms3d #nextPage {
 -webkit-transform: perspective(1000) rotateY(-20deg) translate3d(100%, 0, -400px) !important;
 -moz-transform: perspective(1000) rotateY(-20deg) translate3d(100%, 0, -400px) !important;
 -o-transform: perspective(1000) rotateY(-20deg) translate3d(100%, 0, -400px) !important;
 transform: perspective(1000) rotateY(-20deg) translate3d(100%, 0, -400px) !important; }
```
